### ISSUE TITLE
Lotta CSS issues??

### ISSUE THREAD

**Issue by starrchen** [ga-wdi-exercises/project4#133]
I have two things that I have been trying to do since last night that are just not working?
1. Bootstrap accordion collapse: I'm slightly obsessed with the accordion collapse, but I think that would be the best way for me to display my bucket list items. I was trying to implement the accordion collapse and it wouldn't work, even though other Bootstrap features were working? I have put this on the backburner for now and am looking into other ways to do the accordion collapse. (The Materialize one wasn't working for me either.)
2. Check/click to mark as done: I have been trying to do the simplest version of this, which is including a checkbox and adding a class that would change the background color, for each item. But the problem is even with my test cases, I can't seem to add a class.

I haven't pushed anything for #2 yet, but essentially when I try to copy+paste [this fiddle](http://jsfiddle.net/YQD7c/1/) for testing, I can't get it to add a class to the numbers. :(

Would love some insight as to why some of the Javascript isn't working, as I have tested out my `script.js`with a console log and that is working. :( :(

Repo is here: https://github.com/starrchen/dc-bucket-list

**Comment by RobertAKARobin** [comment]
1. I'd say ask on StackOverflow.

``` html
<input type="checkbox" id="hello" />
<label for="hello">Click me</label>
```

``` css
input[type=checkbox]{
  display:none;
}
input[type=checkbox]+label{
  background-color:blue;
}
input[type=checkbox]:checked+label{
  background-color:red;
}
```
