### ISSUE TITLE
portfolio page not rendering correctly when launched via githubpages

### ISSUE THREAD

**Issue by pootsmagoots** [ga-wdi-exercises/project4#458]
Essentially my webpage looks just find on my local repo. I then launched my website and all the spacing when out of whack. I thought this was due to my flex, but that does not seem to be the case.

<img width="1440" alt="screen shot 2017-04-04 at 12 33 42 pm" src="https://cloud.githubusercontent.com/assets/20207879/24667919/07174562-1933-11e7-937b-aad531232567.png">

This is the local repo working as intended.

<img width="1440" alt="screen shot 2017-04-04 at 12 35 06 pm" src="https://cloud.githubusercontent.com/assets/20207879/24667966/2d8057b6-1933-11e7-92ef-c20b1c6e3eb9.png">

This is the launched website.

Here is the CSS and the html

```css
.info {
  display: flex;
  flex-wrap: wrap;
  padding-right: 20px;
 padding-left: 330px;
 padding-top: 160px;
 font-family: 'Rokkitt', serif;
 text-shadow: rgba(0,0,0,0.1) -1px 0, rgba(0,0,0,0.1) 0 -1px,
   rgba(255,255,255,0.1) 1px 0, rgba(253,255,255,0.1) 0 1px,
   rgba(0,0,0,0.1) -1px -1px, rgba(255,255,255,0.1) 1px 1px;
   color: white;
   background: grey;
 }
.img-circle{
  display: flex;
  flex-wrap: wrap;
box-shadow: 10px 10px 5px black;
background-image: url("img/travis.jpg");
background-repeat: no-repeat;
background-size: cover;
width: 195px;
height: 250px;
border-radius: 30%;
}
```

```html
div class="info"
p
  Hello there, welcome to my portfolio page. My story is rather simple. Have you ever
  had that feeling with a job that makes you feel a little empty inside? Like there is something missing?
  I had that feeling, in fact I had that feeling for quite some time. However, along
  came computer programming and that forever has changed my life. Nothing has quite
  changed me so much (outside of my beautiful wife) than computer programming. I
  have spent countless hours reading documentation, coding along with classes;
  once you experience seeing something that you, you have created, there is
  nothing quite like it. This has grown into my passion, and while there are challenges,
  the gratification that goes along with coding is truly something special. So with that,
  thanks for stopping by and hopefully I might become the developer you're looking for.
/p
/div


 div class="welcome_container"
  h2Travis Batts</h2>
  h4Web Developer Engineer/h4
  img class="img-circle" /
 /div
```
